# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/user/vivado_proje/aircon/aircon.cache/wt [current_project]
set_property parent.project_path C:/Users/user/vivado_proje/aircon/aircon.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.2 [current_project]
read_verilog -library xil_defaultlib C:/Users/user/vivado_proje/aircon/aircon.srcs/sources_1/new/aircon.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top aircon -part xc7z020clg484-1


write_checkpoint -force -noxdef aircon.dcp

catch { report_utilization -file aircon_utilization_synth.rpt -pb aircon_utilization_synth.pb }
